[package]
# Semantic Versionning is used: https://semver.org/
version = "1.1.1"

# The title and description fields are primarily for displaying extension info in UI
title = "Bookshelf Generator 1.1.1"
description="A procedural modeling tool for creating bookshelves with arrayed books."
author = "Matias Codesal"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"
changelog = "docs/CHANGELOG.md"

# preview_image = ""
icon = "data/icon.png"

# Preview to show in the extension manager
preview_image = "data/preview.png"

# URL of the extension source repository.
repository = "https://github.com/mati-nvidia/omni-bookshelf-generator"

# One of categories for UI.
category = "Modeling"

# Keywords for the extension
keywords = ["modeling", "procedural", "pointinstancer", "instancing", "book", "bookshelf", "bookcase"]


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}
"omni.usd" = {}

# Main python module this extension provides, it will be publicly available as "import maticodes.generator.bookshelf".
[[python.module]]
name = "maticodes.generator.bookshelf"

